# Mock Classes to simulate an object that can be accessed with the dot notation, just like the output
# generated by the subprocess.run method (.stdout, .stderr)
class Output:
            stdout = ""
            stderr = ""

class MockedGet:
    def get(self, something):
        return ["123456"]

class MockedRequest:
    headers = MockedGet()
    def get_json(self):
        return MockedGet()

class MockedGetConnections:
    def get(self, something):
        return {'username': 'username', 'ip': 'ip', 'podmanSocketPath': 'podmanSocketPath'}

class MockedRequestConnections:
    headers = MockedGetConnections()
    def get_json(self):
        return MockedGetConnections()

class MockedJson:
    def loads(self, something):
        return something

SUCCESS = 200
ERROR = 400
